Assignment

In [2]:
# Exercise 1
# create a list containing mouse and charger, add phone, add pen,
# remove charger, add battery, remove phone.

In [1]:
items = ["mouse", "charger"]

In [2]:
items.append("phone")

In [3]:
items.append("pen")

In [4]:
items.remove("charger")

In [5]:
items.append("battery")

In [6]:
items.remove("phone")

In [8]:
items

['mouse', 'pen', 'battery']

In [9]:
#Exercise 2
# create a dictionary of 4 students of different names and assign random colors to them.
# write a print out statement using the template below:

# students_name favourite color is color_name

# create a dictionary of 4 students and assign random colors
Student_1 = {"Name" : "Mariam",
             "color" : "Black"}
Student_2 = {"Name" : "Tunde",
             "color" : "Blue"}
Student_3 = {"Name" : "Ajoke",
             "color" : "White"}
Student_4 = {"Name" : "Rokibat",
             "color" : "Purple"}

In [10]:
print(Student_1["Name"], "favourite colour is", Student_1["color"])

Mariam favourite colour is Black

Exercise 3

In [11]:
# Exercise 3
# Check Divisibility by 5:
#    - Write a Python program that takes an integer as input and checks if it is divisible by 5.

number = int(input("Enter an integer: "))
if number % 5 == 0:
    print(f"{number} is divisible by 5.")
else:
    print(f"{number} is not divisible by 5.")

9 is not divisible by 5.

In [ ]:
# Exercise 4A
#  - write a program that ask for your grade
#  - prints out fail if your grade is lesser than 40
#  - print out pass if its higher than 40 but less than 50
#  - out credit if its higher than 50 but less than 70
#  - print out excellent if its higher than 70


# EXERCISE 4B
# DESIGN THE UNILAG GRADING SYSTEM USING PYTHON
# YOUR PRINT OUT STATEMENT SHOULD LOOK LIKE THIS
# YOU HAD 21 IN YOUR CA AND 50 IN YOUR EXAM. THATS A GRADE OF A

In [14]:
# Exercise 4A
#  - write a program that ask for your grade
#  - prints out fail if your grade is lesser than 40
#  - print out pass if its higher thanS 40 but less than 50
#  - out credit if its higher than 50 but less than 70
#  - print out excellent if its higher than 70
# SOLUTION TO 4A
grade = int(input("Enter your grade: "))
if grade > 0 and grade < 40:
  print("fail")
elif grade >= 40 and grade < 50:
    print("pass")
elif grade >= 50 and grade < 70:
      print("credit")
elif grade >= 70 and grade <= 100:
  print("excellent")
else:
    print( 'enter number between 1 to 100' )

enter number between 1 to 100

In [ ]:
# EXERCISE 4B
# DESIGN THE UNILAG GRADING SYSTEM USING PYTHON
# YOUR PRINT OUT STATEMENT SHOULD LOOK LIKE THIS
# YOU HAD 21 IN YOUR CA AND 50 IN YOUR EXAM. THATS A GRADE OF A
# SOLUTION TO 4B
 
CA = int(input("Enter your CA score: "))
EXAM = int(input("Enter your Exam score: "))

if not (0 <= CA <= 30):
    print("Invalid CA score! CA must be between 0 and 30.")
elif not (0 <= EXAM <= 70):
    print("Invalid Exam score! Exam must be between 0 and 70.")
else:
    TOTAL = CA + EXAM
    if TOTAL >= 70:
        grade = 'A'
    elif TOTAL >= 60:
        grade = 'B'
    elif TOTAL >= 50:
        grade = 'C'
    elif TOTAL >= 45:
        grade = 'D'
    elif TOTAL >= 40:
        grade = 'E'
    else:
        grade = 'F'

    print(f"You had {CA} in your CA and {EXAM} in your exam. That's a grade of {grade}.")

You had 25 in your CA and 56 in your exam. That's a grade of A.

In [18]:
# Exercise 5
# Iterate throught the list of numbers and add 4 to each of them.[2,4,5,7,8,9,89,67,43]

numbers = [2,4,5,7,8,9,89,67,43]
for i in numbers:
  print(i + 4)

6
8
9
11
12
13
93
71
47

In [ ]:
# Exercise 6
# INDEX LOCATIONS ASSIGNMENT
# num = [20,76,56,1,62,43,89,0,10,78]

# 1. Return the last number.
# 2. Return all numbers from the 3rd index position.
# 3. Return all numbers before the last three numbers.
# 4. Start from the 3rd index and end at the second-to-last index.
# 5. Return all numbers between the 4th and 8th index positions.
# 6. Return all numbers except the last.
# 7. Return all numbers except the first and last numbers.
# 8. Add the numbers at index positions 3 and 7.

In [5]:
# solution to Exercise 6

num = [20,76,56,1,62,43,89,0,10,78]

In [3]:
num[:-3]

[20, 76, 56, 1, 62, 43, 89]

In [6]:
num[3:]

[1, 62, 43, 89, 0, 10, 78]

In [ ]:
# 1. Return the last number.

num[-1]

In [3]:
# 2. Return all numbers from the 3rd index position.

num[2:]

[56, 1, 62, 43, 89, 0, 10, 78]

In [4]:
num

[20, 76, 56, 1, 62, 43, 89, 0, 10, 78]

In [5]:
# 3. Return all numbers before the last three numbers.

num[:7]

[20, 76, 56, 1, 62, 43, 89]

In [6]:
# 4. Start from the 3rd index and end at the second-to-last index.

num[2:9]

[56, 1, 62, 43, 89, 0, 10]

In [7]:
num

[20, 76, 56, 1, 62, 43, 89, 0, 10, 78]

In [8]:
# 5. Return all numbers between the 4th and 8th index positions.
num[3:8]

[1, 62, 43, 89, 0]

In [9]:
# 6. Return all numbers except the last.
num[:-1]

[20, 76, 56, 1, 62, 43, 89, 0, 10]

In [10]:
# 7. Return all numbers except the first and last numbers.
num[1:9]

[76, 56, 1, 62, 43, 89, 0, 10]

In [11]:
num[1:-1]

[76, 56, 1, 62, 43, 89, 0, 10]

In [ ]:
# 8. Add the numbers at index positions 3 and 7.

num[3]+num[7]

In [ ]:
# Exercise 7
# write a funtion that takes in 3 number and tell which is the largestor highest

In [17]:
# solution to Exercise 7

def largest_number(num_1, num_2, num_3):
  if num_1 > num_2 and num_1 > num_3:
    print(f"{num_1} is the largest number")
  elif num_2 > num_1 and num_2 > num_3:
    print(f"{num_2} is the largest number")
  else:
    print(f"{num_3} is the largest number")

In [18]:
largest_number( 5,6,7)

7 is the largest number

# OR

In [20]:
def largest_number():
    num_1 = int(input("Enter first number: "))
    num_2 = int(input("Enter second number: "))
    num_3 = int(input("Enter third number: "))

    if num_1 > num_2 and num_1 > num_3:
        print(f"{num_1} is the largest number")
    elif num_2 > num_1 and num_2 > num_3:
        print(f"{num_2} is the largest number")
    else:
        print(f"{num_3} is the largest number")

In [21]:
largest_number()

5 is the largest number

In [ ]:
# ASSIGNMENT (EXERCISE 8)

# 1 Create values ranging from 0 to 11, and 0 to 12.
# Return the values from 8 to 10, and 10 to 12 respectively.

# 2 Create values ranging from 3 to 500, and 100 to 250.
# Return the values from 350 to 360, and 100 to 110 respectively.

# 3 Create values ranging from 100 to 110, and 50 to 70.
# Return the values from 105 to 110, and the last 9 numbers respectively.

# 4 Create values ranging from 200 to 250.
# Multiply the last 10 values by 10, and then divide the result by 2.

# 5 Create values ranging from 2000 to 2100.
# Find the mean of the values and multiply it by 10.

# 6 Create values ranging from 10 to 20, and 20 to 30.
# Return the sum of the last 10 values of the first list and the first 10 values of the second list.

# 7 Create values ranging from 5 to 20, and 100 to 200.
# Return the multiplication of the last 10 values of the first list and the first 10 values of the second list.

In [26]:
# 1 Create values ranging from 0 to 11, and 0 to 12.
# Return the values from 8 to 10, and 10 to 12 respectively.

values1 = list(range(0, 12))
values2 = list(range(0, 13))

print(values1[8:11])
print(values2[10:13])

[8, 9, 10]
[10, 11, 12]

In [28]:
# 2 Create values ranging from 3 to 500, and 100 to 250.
#Return the values from 350 to 360, and 100 to 110 respectivelyvalues1 = list(range(0, 12))x = list(range(3, 501))
x = list(range(3,501))
print(x[347:358])
print(x[97:108])

[350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360]
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [29]:
y = list(range(100, 251))
print(y[0:11])

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [30]:
# 3 Create values ranging from 100 to 110, and 50 to 70.
# Return the values from 105 to 110, and the last 9 numbers respectively.

a = list(range(100, 111))
b = list(range(50, 71))
print( a[5:11])
print(b[-9:])

[105, 106, 107, 108, 109, 110]
[62, 63, 64, 65, 66, 67, 68, 69, 70]

In [32]:
# 4 Create values ranging from 200 to 250.
# Multiply the last 10 values by 10, and then divide the result by 2.
c = list(range(200, 251))
for i in c[-10:]:
  print(i*10/2)

1205.0
1210.0
1215.0
1220.0
1225.0
1230.0
1235.0
1240.0
1245.0
1250.0

In [3]:
# 4 Create values ranging from 200 to 250.
# Multiply the last 10 values by 10, and then divide the result by 2.
import numpy as np
z = np.arange(200,251)
y = z[-10:] 
result = y * 10
print(result / 2)

[1205. 1210. 1215. 1220. 1225. 1230. 1235. 1240. 1245. 1250.]

In [4]:
# 5 Create values ranging from 2000 to 2100.
# Find the mean of the values and multiply it by 10.

import numpy as np
# values = np.arange(2000, 2101)  # values = np.array(list(range(2000, 2101)))
values = np.array(list(range(2000, 2101)))
mean_value = np.mean(values)
result = mean_value * 10

print("Mean:", mean_value)
print("Result:", result)

Mean: 2050.0
Result: 20500.0

In [5]:
# 5 Create values ranging from 2000 to 2100.
# Find the mean of the values and multiply it by 10.

values = list(range(2000, 2101))
mean_value = sum(values) / len(values)
result = mean_value * 10

print("Mean:", mean_value)
print("Result:", result)

Mean: 2050.0
Result: 20500.0

In [6]:
import numpy as np
values = np.array(list(range(2000, 2101)))
mean_value = np.mean(values)
result = mean_value * 10

print("Mean:", mean_value)
print("Result:", result)

Mean: 2050.0
Result: 20500.0

In [8]:
#  6 Create values ranging from 10 to 20, and 20 to 30.
# Return the sum of the last 10 values of the first list and the first 10 values of the second list.

# f = np.arange(10, 21)
f = np.array(list(range(10,21)))
# g = np.arange(20, 31)
g = np.array(list(range(20,31)))
h = f[-10:]
i = g[:10]

result = np.sum(h) + np.sum(i)
print(result)

400

In [9]:
#  6 Create values ranging from 10 to 20, and 20 to 30.
# Return the sum of the last 10 values of the first list and the first 10 values of the second list.
f = list(range(10, 21))   # [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
g = list(range(20, 31))   # [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

# Extract parts
h = f[-10:]   # last 10 values of f
i = g[:10]    # first 10 values of g

# Compute result
result = sum(h) + sum(i)
print(result)

400

In [10]:
# 7 Create values ranging from 5 to 20, and 100 to 200.
# Return the multiplication of the last 10 values of the first list and the first 10 values of the second list.

value_1 = np.array(list(range(5,21)))
value_2 = np.array(list(range(100,201)))
a = value_1[-10:]
b = value_2[:10]

result = a * b
print(result)

[1100 1212 1326 1442 1560 1680 1802 1926 2052 2180]

<br><h1><b>CLASS WORK ON EXPLORATORY DATA ANALYSIS</b></h1>

-- Create a dataframe with only the categorical variables in the salary data<br>
-- Create a dataframe with only the numerical variables in the salary data<br>
-- Create a dataframe with only the following job title: 'software designer', 'junior software engineer'.<br>
-- Create a dataframe showing only the job title and the salary of all 'Software Developers' in california and Oklahoma.<br>
-- Who is the highest paid : 'ceo' or 'senior backend engineer'?.<br>
-- what job_title_category will advice me to venture into in the US<br>
-- What is the mean average of 'senior backend engineer' salary<br>
-- Create a dataframe of data workers who earns an average salary within 90,000 and 50,000 in the US<br>
-- Which country has the most paid Data job title category.<br>
-- What is the job_title name is the least paid in the US.<br>
-- Create a dataframe of job_title_category who earns an average salary between 70,000 and 120,000 in the united states<br>
-- Create a Create a dataframe of job_title_category who earns an average salary between 120,000 and and 200,000, and show the employer name of the highest paying company.<br>
-- Data or Software job title Category, who is most paid in the US? Find the mean pay of Data job 
-- Which job title name - inside the Data job title category, is the most paid in the US.<br>
-- Which country has the highest paid Software job title category<br>
-- Create a dataframe that shows the location, job_title_category, and the employer name of: 'front-end developer', 'sr. engineering manager', 'staff software engineer', and 'senior data analyst'. Save this dataframe to a variable name, and show the last two columns, row 10 - 20, row 30 - 40, and row 50 - 60.

In [ ]:
# ASSIGNMENT EXERCISE 9
# title category.<br><h1><b>CLASS WORK ON EXPLORATORY DATA ANALYSIS</b></h1>

# -- Create a dataframe with only the categorical variables in the salary data<br>
# -- Create a dataframe with only the numerical variables in the salary data<br>
# -- Create a dataframe with only the following job title: 'software designer', 'junior software engineer'.<br>
# -- Create a dataframe showing only the job title and the salary of all 'Software Developers' in california and Oklahoma.<br>
# -- Who is the highest paid : 'ceo' or 'senior backend engineer'?.<br>
# -- what job_title_category will advice me to venture into in the US<br>
# -- What is the mean average of 'senior backend engineer' salary<br>
# -- Create a dataframe of data workers who earns an average salary within 90,000 and 50,000 in the US<br>
# -- Which country has the most paid Data job title category.<br>
# -- What is the job_title name is the least paid in the US.<br>
# -- Create a dataframe of job_title_category who earns an average salary between 70,000 and 120,000 in the united states<br>
# -- Create a Create a dataframe of job_title_category who earns an average salary between 120,000 and and 200,000, and show the employer name of the highest paying company.<br>
# -- Data or Software job title Category, who is most paid in the US? Find the mean pay of Data job 
# -- Which job title name - inside the Data job title category, is the most paid in the US.<br>
# -- Which country has the highest paid Software job title category<br>
# -- Create a dataframe that shows the location, job_title_category, and the employer name of: 'front-end developer', 'sr. engineering manager', 'staff software engineer', and 'senior data analyst'. Save this dataframe to a variable name, and show the last two columns, row 10 - 20, row 30 - 40, and row 50 - 60.

In [2]:
import pandas as pd
df = pd.read_csv("salaries_clean.csv")
df.head()

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,job_title_rank,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,stock_value_bonus,comments,submitted_at
0,0,1,opower,"san francisco, ca",CA,US,37.77,-122.41,systems engineer,Engineering,NaN,13.0,2.0,125000.0,5000.0,0.0,5000 shares,Don't work here.,3/21/16 12:58
1,1,3,walmart,"bentonville, ar",AR,US,36.36,-94.20,senior developer,Software,Senior,15.0,8.0,65000.0,NaN,5000.0,"3,000",NaN,3/21/16 12:58
2,2,4,vertical knowledge,"cleveland, oh",OH,US,41.47,-81.67,software engineer,Software,NaN,4.0,1.0,86000.0,5000.0,6000.0,0,NaN,3/21/16 12:59
3,3,6,netapp,waltham,NaN,NaN,NaN,NaN,mts,Other,NaN,4.0,0.0,105000.0,5000.0,8500.0,0,NaN,3/21/16 13:00
4,4,12,apple,cupertino,NaN,NaN,NaN,NaN,software engineer,Software,NaN,4.0,3.0,110000.0,5000.0,7000.0,150000,NaN,3/21/16 13:02

In [3]:
# Create a dataframe with only the categorical variables in the salary data

A = df.select_dtypes(include= ['object','category'])
B = df.select_dtypes(include= 'number')
print("Categorical Dataframe")
display(A.head())
print("\n\nNumerical Dataframe")
display(B.head())

Categorical Dataframe

,employer_name,location_name,location_state,location_country,job_title,job_title_category,job_title_rank,stock_value_bonus,comments,submitted_at
0,opower,"san francisco, ca",CA,US,systems engineer,Engineering,NaN,5000 shares,Don't work here.,3/21/16 12:58
1,walmart,"bentonville, ar",AR,US,senior developer,Software,Senior,"3,000",NaN,3/21/16 12:58
2,vertical knowledge,"cleveland, oh",OH,US,software engineer,Software,NaN,0,NaN,3/21/16 12:59
3,netapp,waltham,NaN,NaN,mts,Other,NaN,0,NaN,3/21/16 13:00
4,apple,cupertino,NaN,NaN,software engineer,Software,NaN,150000,NaN,3/21/16 13:02

Numerical Dataframe

,index,salary_id,location_latitude,location_longitude,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus
0,0,1,37.77,-122.41,13.0,2.0,125000.0,5000.0,0.0
1,1,3,36.36,-94.20,15.0,8.0,65000.0,NaN,5000.0
2,2,4,41.47,-81.67,4.0,1.0,86000.0,5000.0,6000.0
3,3,6,NaN,NaN,4.0,0.0,105000.0,5000.0,8500.0
4,4,12,NaN,NaN,4.0,3.0,110000.0,5000.0,7000.0

In [4]:
num = df.select_dtypes(include= 'number')
print("\n\nNumerical Dataframe")
display(num.head())

Numerical Dataframe

,index,salary_id,location_latitude,location_longitude,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus
0,0,1,37.77,-122.41,13.0,2.0,125000.0,5000.0,0.0
1,1,3,36.36,-94.20,15.0,8.0,65000.0,NaN,5000.0
2,2,4,41.47,-81.67,4.0,1.0,86000.0,5000.0,6000.0
3,3,6,NaN,NaN,4.0,0.0,105000.0,5000.0,8500.0
4,4,12,NaN,NaN,4.0,3.0,110000.0,5000.0,7000.0

In [5]:
# -- Create a dataframe with only the following job title: 'software designer', 'junior software engineer'.

A= df[df['job_title'].isin(['software designer', 'junior software engineer'])]
A

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,job_title_rank,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,stock_value_bonus,comments,submitted_at
813,813,1681,secret ag,zurich,NaN,NaN,NaN,NaN,junior software engineer,Software,Junior,3.0,1.0,92000.0,NaN,6000.0,NaN,NaN,3/21/16 15:38
892,892,1834,nokia,"ottawa, canada",NaN,CA,60.00,-95.00,software designer,Software,NaN,4.0,1.0,56000.0,0.0,0.0,0,NaN,3/21/16 16:23
1361,1361,2708,:),hong kong,NaN,HK,22.27,114.19,junior software engineer,Software,Junior,1.0,1.0,0.0,0.0,0.0,0,NaN,3/22/16 1:02

In [6]:
# -- Create a dataframe showing only the job title and the salary of all 'Software Developers' in california and Oklahoma.

B= [['job_title', 'annual_base_pay', 'location_state']]
B = df[(df['job_title'] == 'software developer') & (df['location_state'].isin(['CA', 'OK']))]
B

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,job_title_rank,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,stock_value_bonus,comments,submitted_at
152,152,364,ibm,"san diego, ca",CA,US,32.71,-117.16,software developer,Software,NaN,9.0,8.0,151000.0,15000.0,5000.0,5000,NaN,3/21/16 13:31
233,233,518,midstage startup,"san francisco, ca",CA,US,37.77,-122.41,software developer,Software,NaN,1.0,1.0,120000.0,0.0,12000.0,1000,NaN,3/21/16 13:41
844,844,1739,zillow group,"irvine, ca",CA,US,33.74,-117.76,software developer,Software,NaN,4.0,1.0,105000.0,2000.0,NaN,1227 RSUs,NaN,3/21/16 15:54

In [8]:
# -- Who is the highest paid : 'ceo' or 'senior backend engineer'?

a = df[['annual_base_pay', 'job_title']]
a = a.loc[a.job_title.isin(['ceo', 'senior backend enginee'])]
a.groupby("job_title")[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = False)

           annual_base_pay
job_title
ceo              2191200.0

In [9]:
#  what job_title_category will advice me to venture into in the US

D = df[['location_country', 'job_title_category', 'job_title','annual_base_pay']]
D = df.loc[(df["location_country"] == 'US')]
D.groupby(['location_country','job_title_category', 'job_title'])[['annual_base_pay']].mean().sort_values(by= 'annual_base_pay', ascending= False).head(1)

                                                                            annual_base_pay
location_country job_title_category job_title
US               Other              professional ice hockey player, center        9250000.0

In [10]:
# - What is the mean average of 'senior backend engineer' salary
E = df[['job_title','annual_base_pay' ]]
E = df.loc[df['job_title'] == 'senior backend engineer']
E.groupby('job_title')['annual_base_pay'].mean()

job_title
senior backend engineer    145000.0
Name: annual_base_pay, dtype: float64

In [11]:
# -- Create a dataframe of data workers who earns an average salary within 90,000 and 50,000 in the US

F = df[["job_title_category", "annual_base_pay"]]
F = df.loc[(df["job_title_category"] == "Data") &   (df["annual_base_pay"].between(50000, 90000))]
F.groupby("job_title_category")["annual_base_pay"].mean()

job_title_category
Data    70780.145
Name: annual_base_pay, dtype: float64

In [12]:
# -- Which country has the most paid Data job title 

G = df[['location_country', 'job_title_category', 'annual_base_pay', 'job_title']]
G = G.loc[df["job_title_category"] == 'Data']
G.groupby(['location_country', 'job_title_category', 'job_title'])[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = False).head(1)

                                                          annual_base_pay
location_country job_title_category job_title
US               Data               senior data engineer         145000.0

In [13]:
# -- What is the job_title name is the least paid in the US.
H = df[['job_title', 'location_country', 'annual_base_pay']]
H = H.loc[df["location_country"]== 'US']
H.groupby(['location_country',  'job_title'])[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = True).head(1)

                            annual_base_pay
location_country job_title
US               founder                0.0

In [14]:
# -- Create a dataframe of job_title_category who earns an average salary between 70,000 and 120,000 in the united states

I = df[["job_title_category", "annual_base_pay", "location_country"]]
I = df.loc[(df["location_country"] == "US") &   (df["annual_base_pay"].between(70000, 120000))]
I.groupby("job_title_category")["annual_base_pay"].mean()

job_title_category
Applied Science    75000.000000
Data               92250.000000
Engineering        98160.677419
Management         91236.842105
Other              95750.000000
Software           97245.993590
Web                89673.974118
Name: annual_base_pay, dtype: float64

In [15]:
# -- Create a Create a dataframe of job_title_category who earns an average salary between 120,000 and and 200,000, and show the employer name of the highest paying company.

I = df[["job_title_category", "annual_base_pay", "employer_name"]]
I = df.loc[df["annual_base_pay"].between(120000, 200000)]
I.groupby(["job_title_category", "employer_name"])["annual_base_pay"].mean().reset_index().sort_values(by="annual_base_pay", ascending=False)

    job_title_category        employer_name  annual_base_pay
57         Engineering                 self         200000.0
122              Other                   dd         200000.0
125              Other  economic consulting         200000.0
184           Software          b2b startup         200000.0
78          Management            atlassian         195000.0
..                 ...                  ...              ...
22         Engineering              craftsy         120000.0
311           Software           varagesale         120000.0
314           Software                 visa         120000.0
313           Software    video game studio         120000.0
319           Software        ycs12 startup         120000.0

[339 rows x 3 columns]

In [178]:
# -- Data or Software job title Category, who is most paid in the US? Find the mean pay of Data job 
J = df[['job_title_category', 'location_country', 'annual_base_pay']]
J = J.loc[df.job_title_category.isin(['Data', 'software']) & (df['location_country'] == "US")]
J.groupby(['location_country',  'job_title_category'])[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = True)

                                     annual_base_pay
location_country job_title_category
US               Data                   78558.928571

In [ ]:
# -- Which job title name - inside the Data job title category, is the most paid in the US.
K = df[['job_title', 'location_country','job_title_category', 'annual_base_pay']]
K = K.loc[(df["location_country"]== 'US') & (df['job_title_category'] == "Data")]
K.groupby(['job_title', 'location_country', 'job_title_category'])[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = False).head(1)

                                                          annual_base_pay
job_title            location_country job_title_category
senior data engineer US               Data                       145000.0

In [181]:
# -- Which country has the highest paid Software job title category.
L = df[['job_title', 'location_country','job_title_category', 'annual_base_pay']]
L = L.loc[df['job_title_category'] == "Software"]
L.groupby(['job_title', 'location_country', 'job_title_category'])[['annual_base_pay']].mean().sort_values(by = 'annual_base_pay', ascending = False).head(1)

                                                        annual_base_pay
job_title          location_country job_title_category
software architect HU               Software                  6000000.0

In [12]:
# -- Create a dataframe that shows the location, job_title_category, and the employer name of: 'front-end developer', 'sr. engineering manager', 'staff software engineer', and 'senior data analyst'. Save this dataframe to a variable name, and show the last two columns, row 10 - 20, row 30 - 40, and row 50 - 60.
A = df[['job_title', 'job_title_category', 'location_country', 'employer_name']]
A = A.loc[df.job_title.isin(['front-end developer', 'sr. engineering manager', 'staff software engineer','senior data analyst'])]
A.groupby(['location_country', 'job_title_category', 'employer_name']).size().reset_index()

,location_country,job_title_category,employer_name,0
0,CA,Software,mozilla,1
1,US,Data,ad-tech,1
2,US,Software,box,1
3,US,Software,ibm,1
4,US,Web,freelance,1
5,US,Web,mainz brady group - contractor at nike,1
6,US,Web,netspend,1

In [ ]:
# # ASSIGNMENT (EXERCISE 10)
# # workers data
# -- What is the average age of each Education Level.

# -- Of all education level, what level has the most capital gain

# -- What race has the most capital loss

# -- What is the total capital loss for all Female that is Divorced

# -- In your advice, if you are gonna give a loan, what Marital Status would you consider

# -- SHow the total capital gain of all Doctorate education level

# -- Who works the most total hours per week in the varying Occupation. What is the average capital gain of this class.

# -- What race is divorces the most.

# -- What Marital Status works the most total hours. What race mostly constitute this status

In [2]:
import pandas as pd
dx = pd.read_csv("workers_data.csv")
dx.head(2)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income_>50K
0,67,Private,366425,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Male,99999,0,60,United-States,1
1,17,Private,244602,12th,8,Never-married,Other-service,Own-child,White,Male,0,0,15,United-States,0

In [3]:
# -- What is the average age of each Education Level.
dx.groupby('education')['age'].mean().head(3)

education
10th    37.628000
11th    31.803886
12th    32.207836
Name: age, dtype: float64

In [4]:
# -- Of all education level, what level has the most capital gain
dx.groupby('education')['capital-gain'].mean().head(1)

education
10th    266.5072
Name: capital-gain, dtype: float64

In [5]:
# -- What race has the most capital loss
dx.groupby('race')['capital-gain'].mean().head(1)

race
Amer-Indian-Eskimo    556.92399
Name: capital-gain, dtype: float64

In [6]:
# -- What is the total capital loss for all Female that is Divorced
A = dx[['gender', 'marital-status', 'capital-loss']]
A =dx.loc[(dx["marital-status"]== 'Divorced') & (dx['gender'] == "Female")]
A.groupby(['marital-status', 'gender'])['capital-loss'].mean()

marital-status  gender
Divorced        Female    55.487791
Name: capital-loss, dtype: float64

In [7]:
dx.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income_>50K'],
      dtype='object')

In [8]:
# -- In your advice, if you are gonna give a loan, what Marital Status would you consider
B = dx[['marital-status', 'capital-loss']]
B.groupby('marital-status')['capital-loss'].mean().tail()

marital-status
Married-civ-spouse       121.060307
Married-spouse-absent     69.614035
Never-married             54.914973
Separated                 58.098457
Widowed                   81.151760
Name: capital-loss, dtype: float64

In [9]:
B = dx[['marital-status', 'capital-gain']]
B.groupby('marital-status')['capital-gain'].mean()

marital-status
Divorced                  801.825992
Married-AF-spouse        3546.774194
Married-civ-spouse       1754.772175
Married-spouse-absent     689.194737
Never-married             397.106594
Separated                 602.175606
Widowed                   617.998534
Name: capital-gain, dtype: float64

In [10]:
# -- SHow the total capital gain of all Doctorate education level
C = dx[['education',  'capital-gain']]
C =dx.loc[dx["education"]== 'Doctorate']
C.groupby('education')['capital-gain'].sum()

education
Doctorate    3165535
Name: capital-gain, dtype: int64

In [11]:
# -- Who works the most total hours per week in the varying Occupation. What is the average capital gain of this class.
D = dx[['occupation', 'hours-per-week', 'capital-gain']]
D.groupby('occupation')['capital-gain'].mean()

occupation
Adm-clerical          494.315148
Armed-Forces          561.384615
Craft-repair          700.829317
Exec-managerial      2296.193789
Farming-fishing       722.637240
Handlers-cleaners     292.164004
Machine-op-inspct     317.348580
Other-service         223.345324
Priv-house-serv       179.120000
Prof-specialty       2854.010692
Protective-serv       673.446224
Sales                1268.312991
Tech-support          707.229372
Transport-moving      421.095238
Name: capital-gain, dtype: float64

In [12]:
# -- What race is divorces the most.
E = dx[['race', 'marital-status']]
E =dx.loc[dx['marital-status'] == 'Divorced']
E.groupby('race').size()

race
Amer-Indian-Eskimo      78
Asian-Pac-Islander     103
Black                  634
Other                   38
White                 5118
dtype: int64

In [13]:
# -- What Marital Status works the most total hours. What race mostly constitute this status
F = dx[['race', 'marital-status', 'hours-per-week']]
F.groupby(['race', 'marital-status'])['hours-per-week'].mean().head()

race                marital-status
Amer-Indian-Eskimo  Divorced                 39.333333
                    Married-civ-spouse       43.111842
                    Married-spouse-absent    40.000000
                    Never-married            39.141892
                    Separated                38.000000
Name: hours-per-week, dtype: float64